version: 2.1

executors:
  gitleaks:
    docker:
      - image: zricethezav/gitleaks:latest
  node:
    docker:
      - image: cimg/node:lts

#
# Commands - https://circleci.com/docs/2.0/configuration-reference/#commands
#
# A command defines a sequence of steps as a map to be executed in a job,
# enabling you to reuse a single command definition across multiple jobs
#

commands:
  restore-cache-node_modules:
    description: "Restore cache - node_modules"
    steps:
      - restore_cache:
          keys:
            - v1-node_modules-{{ checksum "package-lock.json" }}
            - v1-node_modules-
  save-cache-node_modules:
    description: "Update cache - node_modules"
    steps:
      - save_cache:
          key: v1-node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  restore-cache-npm:
    description: "Restore cache - .npm"
    steps:
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package-lock.json" }}
            - v1-npm-
  save-cache-npm:
    description: "Update cache - .npm"
    steps:
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - .npm

#
# Jobs - https://circleci.com/docs/2.0/configuration-reference/#jobs
#
# Groups of comands used in one or more Workflows
#
# - Keep GLOBAL variable usage at a minimum
# - Prioritize `parameters` usage
#

jobs:
  detect-secrets:
    executor: gitleaks
    steps:
      - checkout
      - run:
          name: "[gitleaks] Detect secrets in repository history"
          command: |
            gitleaks detect --redact --verbose

  setup:
    executor: node
    steps:
      - checkout
      - restore-cache-node_modules
      - restore-cache-npm
      - run:
          name: "[npm] Install packages"
          command: "npm run setup"
      - save-cache-node_modules
      - save-cache-npm

  test:
    executor: node
    steps:
      - checkout
      - restore-cache-node_modules
      - run:
          name: "[eslint,markdownlint]: Lint"
          command: "npm run lint"

  release-npm:
    executor: node
    steps:
      - checkout
      - restore-cache-node_modules
      - run:
          name: "[semantic-release]: Publish package to npm"
          command: "npm run release"

#
# Workflows - https://circleci.com/docs/2.0/workflows/
#
# - Treat workflows as piping commands (cmd1 -p1 lorem | cmd2 | ... | cmdN) or
#   function composition
# - Use/set GLOBAL variables if they are used in more than 2 jobs
#

workflows:
  npm_publish:
    jobs:
      - detect-secrets:
          filters:
            branches:
              only: [master]
      - setup:
          requires: [detect-secrets]
      - test:
          requires: [setup]
      - release-npm:
          requires: [test]
          context: ["GitHub Auth", "NPM Auth"]
